# Generated by Django 3.2 on 2022-01-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
    ]
