# Generated by Django 3.2 on 2022-01-27 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_alter_booking_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='table_number',
        ),
        migrations.RemoveField(
            model_name='table',
            name='restaurant_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.restaurant'),
        ),
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.ManyToManyField(related_name='tables', to='booking.Table'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='table',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
